#!/usr/bin/env sh

printf "\nRunning post-commit SonarQube checks...\n"

npm run sonar -- \
  -Dsonar.host.url="${SONAR_HOST_URL:-http://192.168.50.104:9000}" \
  -Dsonar.token="${SONAR_TOKEN}" || exit 1

printf "\nPost-commit check pass\n"
