#!/usr/bin/env sh

echo "Running pre-commit checks..."

npm run sonar -- \
  -Dsonar.host.url="${SONAR_HOST_URL:-http://192.168.50.104:9000}" \
  -Dsonar.token="${SONAR_TOKEN}" || exit 1

echo "Pre-commit check pass"
